name: torrent_media
description: Easy way to search torrent and see it on your TV

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  percent_indicator: ^2.1.1+1
  transparent_image: ^1.0.0
  flutter_svg: ^0.15.0

  # Bloc for state management
  flutter_bloc: ^3.1.0

  # Functional programming thingies
  dartz: ^0.8.9

  # Value equality
  equatable: ^1.0.2

  # Service locator
  get_it: ^3.1.0

  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.5
  json_annotation: ^3.0.1
  source_gen: ^0.9.4+7
  build_runner: ^1.7.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lang/